repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
        exclude: ^(legacy_tests/|fix_.*\.py|.*\.md)
    -   id: check-merge-conflict

-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - flake8-quotes
          - flake8-comprehensions
          - flake8-pytest-style
        exclude: ^(legacy_tests/)

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.13
        args: [--line-length=88]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML, types-setuptools]
        args: [--ignore-missing-imports]
        exclude: ^(legacy_tests/)

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
    -   id: bandit
        args: [--format, json, --severity-level, medium]
        exclude: ^(tests/|legacy_tests/)

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.4.2
    hooks:
    -   id: python-safety-dependencies-check
        files: requirements\.txt$

-   repo: local
    hooks:
    -   id: xenon-complexity
        name: xenon complexity check (C grade or better)
        entry: xenon
        language: python
        args: [--max-absolute, C]
        files: ^goesvfi/.*\.py$
        additional_dependencies: [xenon>=0.9.3]
