repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: debug-statements
        exclude: ^(legacy_tests/|fix_.*\.py|.*\.md)
    -   id: check-merge-conflict

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        exclude: ^(legacy_tests/)
    -   id: ruff-format
        exclude: ^(legacy_tests/)

# Ruff handles both import sorting and formatting, so isort and black are not needed

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
    -   id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
          - types-setuptools
          - types-Pillow
          - types-aiofiles
        args: [--ignore-missing-imports, --disable-error-code=import-untyped]
        exclude: ^(legacy_tests/)

-   repo: local
    hooks:
    -   id: pyright
        name: pyright type checker
        entry: pyright
        language: python
        files: ^goesvfi/.*\.py$
        additional_dependencies: [pyright>=1.1.390, PyQt6>=6.0.0]
        exclude: ^(legacy_tests/)

-   repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
    -   id: bandit
        args: [--format, json, --severity-level, medium, --confidence-level, medium]
        exclude: ^(tests/|legacy_tests/)

# Safety check removed - it only supports Poetry format, not setuptools

-   repo: local
    hooks:
    -   id: xenon-complexity
        name: xenon complexity check (C grade or better)
        entry: xenon
        language: python
        args: [--max-absolute, C]
        files: ^goesvfi/.*\.py$
        additional_dependencies: [xenon>=0.9.3]
