name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # Use Python 3.11 as required by pyproject.toml

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libgl1 libegl1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
          libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 \
          libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 \
          qt6-base-dev xvfb # Install Qt6 dev packages and xvfb for headless GUI tests

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test] # Install package and test dependencies from pyproject.toml

    - name: Test with pytest
      run: |
        xvfb-run pytest # Use xvfb-run for headless GUI tests
