name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"] # Updated to Python 3.13 as required by pyproject.toml

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Enable pip caching

    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libgl1 libegl1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 \
          libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 \
          libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 \
          qt6-base-dev xvfb # Install Qt6 dev packages and xvfb for headless GUI tests

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test] # Install package and test dependencies from pyproject.toml in editable mode

    - name: Run mypy type checking
      run: |
        mypy --strict goesvfi

    - name: Test with pytest (working tests only)
      run: |
        xvfb-run python ./run_working_tests.py # Use xvfb-run for headless GUI tests with working tests only
