# Test Summary Workflow - Provides clean test output
name: Test Summary

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-summary:
    name: Generate Test Summary
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}

    steps:
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: test-results-*
        path: test-results/
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          test-results/**/test-results.xml
        check_name: Test Results Summary
        comment_title: Test Results
        comment_mode: always
        fail_on: nothing
        report_individual_runs: true
        dedup_classes_by_file_name: true
